### ISSUE TITLE
Doesn't work presently

### ISSUE THREAD

**Issue by ashinzekene** [sajeetharan/GitWar#8] opened 2017-10-22 16:58 UTC
I forked your project to work on it but it has issues with fetching from the api. Is it the same on yours. I want to know where to start from

**Comment by sajeetharan** [comment] 2017-10-22 17:25
Hey @ashinzekene , Thanks first of all. The problem is with the api key for github, you need to generate a new key with your github account from the developer portal and replace the key in environment.ts. Then it will be fine

export const environment = {
  production: false,
  apiUrl: 'e3fe83bbb20a95f4b17df7d431a161310813d701'
};

It is there in the documentation. Let me know if it does not work

**Comment by sajeetharan** [comment] 2017-10-23 18:37
hope this issue is sorted now! closing!

**Closed as completed by sajeetharan** 2017-10-23 18:37 UTC
